spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/mail?useUnicode=true&characterEncoding=utf8&nullCatalogMeansCurrent=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 数据库与实体类表字段驼峰映射
  mapper-locations: classpath:mappers/*.xml   # 指定路径下扫描xml配置文件

logging:
  pattern:
    console: " [%thread] %-5level %logger{50} - %msg%n"



